### ISSUE TITLE
poisson blending

### ISSUE THREAD

**Issue by WJShengD** [ChengBinJin/semantic-image-inpainting#3]
Is the input background image of Poisson blending a complete picture? But the complete picture should not be known until it is repaired. If we use the complete original image as the background image of Poisson blending, it seems to be a logical mistake. I don't know if I misunderstood it.

**Comment by ChengBinJin** [comment]
Yes, the input background image of Poisson blending is a complete picture. But before blending, we combined foreground of the generated image and background of the generated image. Even though, we gave a complete image, we didn't use foreground information of the real image. Thank you for your question. If the input image of blending is masked image directly, it will more like a real application.
