### ISSUE TITLE
The experiment didn't work well, it was different from yours.

### ISSUE THREAD

**Issue by zhang123456zhang** [ChengBinJin/semantic-image-inpainting#4]
Hello, after I ran your code, the experiment didn't work well. 
It was different from yours. Is there some details I didn't notice?

**Comment by ChengBinJin** [comment]
The performance highly depends on the DCGAN model. Maybe when training DCGAN, there were happened mode collapse problem. To check this issue, you can estimate DCGAN alone first. If the generated results are same samples and the quality is bad, then it is.

**Comment by UpsilonCLJ** [comment]
I have same question. I still don't known why.

![sample_0](https://user-images.githubusercontent.com/57611114/68562436-9928bf00-0484-11ea-9f6e-de36f78eac9f.png)

The inpaint result 
![center_19](https://user-images.githubusercontent.com/57611114/68562455-b067ac80-0484-11ea-9c20-5364f5547a58.png)

**Comment by ChengBinJin** [comment]
@UpsilonCLJ It's a problem with the DCGAN. This method based on the high quality of the DCGAN. Please make sure DCGAN works well first.

**Comment by UpsilonCLJ** [comment]
Thank you for you reply, and  I also have another question, it's model load failed. I change the self.model_out_dir = own dir in inpaint_solver.py, but it doesn't work. It really confused me.

**Comment by ChengBinJin** [comment]
@UpsilonCLJ 
Please just giving the folder name, not the full path, e.g. '20180704-1746'. The program will find the given model from the model-saving folder automatically. Following is the example.
```
python inpaint_main.py --dataset=celebA  --load_model=20180704-1746 --mask_type=center
```
