### ISSUE TITLE
Load failed

### ISSUE THREAD

**Issue by wkkkkkx** [ChengBinJin/semantic-image-inpainting#6]
Hello, I would like to ask when I evaluate DCGAN and image restoration in the second and third steps. [*] Reading checkpoint...  [!] Load Failed...  seems to be loading the model failed, I want to ask why this is, thank you very much！

**Comment by qivigor** [comment]
@wkkkkkx you can change the    self.model_out_dir = your own dir     in inpaint_solver.py.

**Comment by wkkkkkx** [comment]
thank you very much!

**Comment by ChengBinJin** [comment]
@qivigor thank you for your reply.
